---
default: &default
  corpid: <%= Rails.application.credentials.wechat_corpid! %>
  corpsecret: <%= Rails.application.credentials.wechat_corpsecret! %>
  agentid: <%= Rails.application.credentials.wechat_agentid! %>
  token: <%= Rails.application.credentials.wechat_token! %>
  access_token: "tmp/wechat_access_token"
  encrypt_mode: true
  encoding_aes_key: <%= Rails.application.credentials.wechat_encoding_aes_key! %>
  jsapi_ticket: "tmp/wechat_jsapi_ticket"

production:
  corpid: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_corpid] %>
  corpsecret: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_corpsecret] %>
  agentid: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_agentid] %>
  token: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_token] %>
  timeout: 30,
  access_token: <%= ENV['WECHAT_ACCESS_TOKEN'] %>
  encrypt_mode: true
  encoding_aes_key: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_encoding_aes_key] %>
  jsapi_ticket: <%= ENV['WECHAT_JSAPI_TICKET'] %>
  oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %>  # seconds

staging:
  <<: *default

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default

# Multiple Accounts
#
# wx2_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token2"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket2"
#
# wx2_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx2_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token3"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket3"
#
# wx3_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
