---
default: &default
  corpid: <%= Rails.application.credentials.wechat_corpid! %>
  corpsecret: <%= Rails.application.credentials.wechat_corpsecret! %>
  agentid: <%= Rails.application.credentials.wechat_agentid! %>
  token: <%= Rails.application.credentials.wechat_token! %>
  access_token: "tmp/wechat_access_token"
  encrypt_mode: true
  encoding_aes_key: <%= Rails.application.credentials.wechat_encoding_aes_key! %>
  jsapi_ticket: "tmp/wechat_jsapi_ticket"

production:
  corpid: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_corpid] %>
  corpsecret: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_corpsecret] %>
  agentid: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_agentid] %>
  token: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_token] %>
  timeout: 30,
  access_token: <%= ENV['WECHAT_ACCESS_TOKEN'] %>
  encrypt_mode: true
  encoding_aes_key: <%= Rails.application.credentials[Rails.env.to_sym][:wechat_encoding_aes_key] %>
  jsapi_ticket: <%= ENV['WECHAT_JSAPI_TICKET'] %>
  oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %>  # seconds

staging:
  <<: *default

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default

# Multiple Accounts
#
service_account: &service_account
  appid: <%= Rails.application.credentials.wechat_svca_appid! %>
  secret: <%= Rails.application.credentials.wechat_svca_secret! %>
  access_token: "tmp/wechat_svca_access_token"
  jsapi_ticket: "tmp/wechat_svca_jsapi_ticket"

svca_development:
  <<: *service_account

svca_test:
  <<: *service_account

svca_production:
  <<: *service_account

bi_account: &bi_account
  corpid: <%= Rails.application.credentials.wechat_corpid! %>
  corpsecret: <%= Rails.application.credentials.wechat_bi_corpsecret! %>
  agentid: <%= Rails.application.credentials.wechat_bi_agentid! %>
  access_token: "tmp/wechat_bi_access_token"
  jsapi_ticket: "tmp/wechat_bi_jsapi_ticket"

bi_development:
  <<: *bi_account

bi_test:
  <<: *bi_account

bi_production:
  <<: *bi_account

mini_account: &mini_account
  appid: <%= Rails.application.credentials.wechat_mini_appid! %>
  secret: <%= Rails.application.credentials.wechat_mini_secret! %>
  type: "mp"
  access_token: "tmp/wechat_mini_access_token"
  jsapi_ticket: "tmp/wechat_mini_jsapi_ticket"

mini_development:
  <<: *mini_account

mini_test:
  <<: *mini_account

mini_production:
  <<: *mini_account

mini_corp_account: &mini_corp_account
  corpid: <%= Rails.application.credentials.wechat_corpid! %>
  corpsecret: <%= Rails.application.credentials.wechat_mini_corpsecret! %>
  agentid: <%= Rails.application.credentials.wechat_mini_corp_agentid! %>
  access_token: "tmp/wechat_mini_corp_access_token"
  jsapi_ticket: "tmp/wechat_mini_corp_jsapi_ticket"

mini_corp_development:
  <<: *mini_corp_account

mini_corp_test:
  <<: *mini_corp_account

mini_corp_production:
  <<: *mini_corp_account
